[tools]
bun = "latest"
fzf = "latest"
hadolint = "latest"
java = "26"
node = "26"
opencode = "latest"
uv = "latest"
zig = "latest"
zoxide = "latest"

"cargo:bat" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:git-delta" = "latest"
"cargo:bottom" = "latest"
"cargo:difftastic" = "latest"
"cargo:zellij" = "latest"

# Via GitHub releases
# "github:plenaryapp/superfile" = "latest"
# "kakoune" = "latest"
