[tools]
java = "26"
node = "26"
uv = "latest"
opencode = "latest"
bun = "latest"
hadolint = "latest"

"cargo:bat" = "latest"
"cargo:fd-find" = "latest"
"cargo:ripgrep" = "latest"
"cargo:git-delta" = "latest"
"cargo:bottom" = "latest"
"cargo:difftastic" = "latest"
"cargo:zellij" = "latest"

# Native mise plugins
"zoxide" = "latest"
"fzf" = "latest"

# Via GitHub releases
# "github:plenaryapp/superfile" = "latest"
# "kakoune" = "latest"
